services:
  todoapp:
    image: todoapp
    ports:
      - "80:80"
      - "443:443"
    environment:
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/app/cert.pem
      - ASPNETCORE_Kestrel__Certificates__Default__KeyPath=/app/key.pem
    volumes:
      - /etc/letsencrypt/live/3xjn.dev/cert.pem:/app/cert.pem:ro
      - /etc/letsencrypt/live/3xjn.dev/key.pem:/app/key.pem:ro
    restart: unless-stopped
    working_dir: ./TodoApp