services:
  todo-app:
    image: ${IMAGE_TAG}
    ports:
      - "80:80"
      - "443:443"
    environment:
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/app/cert.pem
      - ASPNETCORE_Kestrel__Certificates__Default__KeyPath=/app/key.pem
      - Mongo__ConnectionString=${MONGO_CONNECTION_STRING}
      - Mongo__DatabaseName=${MONGO_DATABASE_NAME}
      - Mongo__CollectionName=${MONGO_COLLECTION_NAME}
    volumes:
      - ${CERT_PEM}:/app/cert.pem:ro
      - ${KEY_PEM}:/app/key.pem:ro
    restart: unless-stopped