name: CI

on: [push]

jobs:

  deploy:
    if: github.ref == 'refs/head/main'
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Deploy APP
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USERNAME }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          script_stop: true
          command_timeout: 200m
          script: /
            cd /home/root
            git pull
            cd ..
            docker-compose build --force-rom --no-cache --compress
            docker-compose up -d
