name: Build and Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Set lowercase repository name
        id: repo-name
        run: echo "REPO_NAME=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Build Docker image
        run: docker build -t ghcr.io/${{ env.REPO_NAME }}/my-container:latest .

      - name: Push Docker image to GitHub Container Registry
        run: docker push ghcr.io/${{ env.REPO_NAME }}/my-container:latest

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.DROPLET_IP }} >> ~/.ssh/known_hosts

      - name: SSH into Droplet and Deply using Docker Compose
        run: |
          ssh -o ServerAliveInterval=60 -o ServerAliveCountMax=10 -i ~/.ssh/id_rsa ${{ secrets.DROPLET_USERNAME }}@${{ secrets.DROPLET_IP }} << EOF
            echo $GITHUB_PAT | docker login ghcr.io -u 3xjn --password-stdin
            docker pull ghcr.io/${{ env.REPO_NAME }}/my-container:latest
            docker run -d --name my-todo-app ghcr.io/${{ env.REPO_NAME }}/my-container:latest
