name: Build and Push Docker Image to DigitalOcean Droplet
on:
  push:
    branches: [master, main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Cache Docker layers
        id: docker-cache
        uses: actions/cache@v3
        with:
          path: |
            /tmp/.docker-cache
          key: ${{ runner.os }}-docker-${{ hashFiles('**/Dockerfile', '**/*.py', '**/*.js') }}
          restore-keys: |
            ${{ runner.os }}-docker-
      - name: Set up Docker Image Tag
        run: |
          echo "IMAGE_TAG=todoapp:$(date +%s)-${GITHUB_SHA::8}" >> $GITHUB_ENV
      - name: Build Docker image
        run: |
          docker build --cache-from=type=local,src=/tmp/.docker-cache -t "${{ env.IMAGE_TAG }}" .
          echo "Docker image built successfully:"
          docker image ls --format "{{.Repository}}:{{.Tag}}" | grep "todoapp" || echo "Warning: Image not found in list, but build completed"
      - name: Save Docker image to a tar file
        run: |
          docker save ${{ env.IMAGE_TAG }} -o image.tar
          ls -lh image.tar
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.DROPLET_IP }} >> ~/.ssh/known_hosts
      - name: Transfer docker image
        run: |
          scp -i ~/.ssh/id_rsa image.tar ${{ secrets.DROPLET_USERNAME }}@${{ secrets.DROPLET_IP }}:/home/${{ secrets.DROPLET_USERNAME }}/image.tar
      - name: SSH into Droplet and Deploy using Docker
        run: |
          ssh -o ServerAliveInterval=60 -o ServerAliveCountMax=10 -i ~/.ssh/id_rsa ${{ secrets.DROPLET_USERNAME }}@${{ secrets.DROPLET_IP }} << EOF
            set -e
            echo "Loading Docker image..."
            sudo docker load -i /home/${{ secrets.DROPLET_USERNAME }}/image.tar
            echo "Stopping and removing any existing container..."
            sudo docker stop my-container || echo "No container to stop"
            sudo docker rm my-container || echo "No container to remove"
            echo "Running Docker container..."
            sudo docker run -d --name my-container \
              -p 443:443 -p 80:80 \
              -v /etc/letsencrypt/live/3xjn.dev/:/app/certs/:ro \
              -v /var/www/html/.well-known/:/app/wwwroot/.well-known/ \
              --env MONGO__ConnectionString="${{ secrets.MONGO_CONNECTION_STRING }}" \
              --env MONGO__DatabaseName="${{ secrets.MONGO_DATABASE_NAME }}" \
              --env MONGO__CollectionName="${{ secrets.MONGO_COLLECTION_NAME }}" \
              ${{ env.IMAGE_TAG }}
            echo "Cleaning up..."
            rm /home/${{ secrets.DROPLET_USERNAME }}/image.tar
            echo "Deployment completed successfully!"
          EOF
